apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trivy-components
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '130'
spec:
  project: default
  source:
    repoURL: <GIT_REPOSITORY_GIT_URL>
    path: gitops_pipelines/delivery/clusters/cc_cluster/core_services/components/devsecops/trivy
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: trivy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
