apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeflow
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '180'
spec:
  project: core
  source:
    repoURL: git@github.com:CGDevX-Demo/delta.git
    path: gitops-pipelines/delivery/clusters/cc-cluster/core-services/components/ml-services/kubeflow/
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: kubeflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
    retry:
      limit: 10
      backoff:
        duration: 30s
        maxDuration: 15m0s
        factor: 2

  ignoreDifferences:
    - group: apps
      kind: Deployment
      jqPathExpressions:
      - '.spec.template.spec.containers[].resources'
    - group: apps
      kind: StatefulSet
      jqPathExpressions:
      - '.spec.template.spec.containers[].resources'
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
      jqPathExpressions:
      - '.rules'
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jqPathExpressions:
      - '.webhooks[].clientConfig.caBundle'
      - '.webhooks[].clientConfig.service.path'
      - '.webhooks[].namespaceSelector'
      - '.webhooks[].objectSelector'
      - '.webhooks[].reinvocationPolicy'
      - '.webhooks[].rules'
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jqPathExpressions:
      - '.webhooks[].clientConfig.caBundle'
      - '.webhooks[].clientConfig.service.path'
      - '.webhooks[].namespaceSelector'
      - '.webhooks[].objectSelector'
      - '.webhooks[].reinvocationPolicy'
      - '.webhooks[].failurePolicy'
      - '.webhooks[].rules'
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: inferenceservices.serving.kserve.io
      jqPathExpressions:
      - '.spec.conversion.webhook.clientConfig.caBundle'