apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: perfectscale-components
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '180'
spec:
  project: core
  source:
    repoURL: <GIT_REPOSITORY_GIT_URL>
    path: gitops-pipelines/delivery/clusters/cc-cluster/core-services/components/perfectscale
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: perfectscale
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        maxDuration: 15m0s
        factor: 2
