apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workloads-appset
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '200'
spec:
  project: core
  source:
    repoURL: <GIT_REPOSITORY_GIT_URL>
    path: gitops-pipelines/delivery/clusters/cc-cluster/workloads
    targetRevision: HEAD
    directory:
      exclude: '{workload-template.yaml}'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 5m0s
        factor: 2
