apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-secret-store
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '40'
spec:
  project: core
  source:
    repoURL: <GIT_REPOSITORY_GIT_URL>
    path: gitops-pipelines/delivery/clusters/cc-cluster/core-services/components/kube-system/cluster-secret-store
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 5m0s
        factor: 2
