apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor-components
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '45'
spec:
  project: default
  source:
    repoURL: <GIT_REPOSITORY_GIT_URL>
    path: gitops-pipelines/delivery/clusters/cc-cluster/core-services/components/harbor
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true