apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarqube-components
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '45'
spec:
  project: core
  source:
    repoURL: <GIT_REPOSITORY_GIT_URL>
    path: gitops-pipelines/delivery/clusters/cc-cluster/core-services/components/sonarqube
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: sonarqube
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
