apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator-components
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '30'
spec:
  project: default
  source:
    repoURL: <GIT_REPOSITORY_GIT_URL>
    path: platform/gitops_pipelines/delivery/clusters/cc_cluster/core_services/components/kube-system/external-secrets-operator
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
