apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-toolkit-velero-wait
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k8s-toolkit-velero-wait
  namespace: velero
rules:
  - apiGroups: [ apps ]
    resources: [ deployments ]
    verbs: [ get, list, watch ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-toolkit-velero-wait
  namespace: velero
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: k8s-toolkit-velero-wait
subjects:
  - kind: ServiceAccount
    name: k8s-toolkit-velero-wait
    namespace: monitoring
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '5'
  name: wait-velero
  namespace: monitoring
spec:
  template:
    spec:
      serviceAccountName: k8s-toolkit-velero-wait
      containers:
        - name: wait
          image: registry.hub.docker.com/bitnami/kubectl:latest
          imagePullPolicy: IfNotPresent
          args:
            - "rollout"
            - "status"
            - "deployment"
            - "velero"
            - "--namespace=velero"
            - "--timeout=120s"
            - "--watch=true"
      restartPolicy: OnFailure
