apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/kubernetes/autoscaler/vertical-pod-autoscaler/deploy?ref=vertical-pod-autoscaler-1.3.1
  - self-signed-cert.yaml

patches:
  - path: vpa-admission-controller-deployment.yaml

transformers:
  - label-transformer.yaml
