apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

# To upgrade ArgoCD, increment the version here
# https://github.com/argoproj/argo-cd/tags
resources:
  - github.com:argoproj/argo-cd.git/manifests/ha/cluster-install?ref=v2.8.4
  - argocd-namespace.yaml

patches:
  - path: argocd-cm.yaml
  - path: argocd-cmd-params-cm.yaml
  - path: argocd-rbac-cm.yaml

generatorOptions:
  disableNameSuffixHash: true