CloudGeometry/cgdevx-core:
  - LICENSE
  - gitignore
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
  - QUICKSTART.md
  - README.md
  - source: platform/
    deleteOrphaned: true
  - source: tools/
    deleteOrphaned: true
