apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: core
  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 0.36.1
    helm:
      values: |-
        nameOverride: argo
        images:
          pullPolicy: IfNotPresent
        executor:
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1
              memory: 1024Mi
        server:
          authMode: sso
          serviceAccount:
            create: true
            name: argo-server
            annotations:
              eks.amazonaws.com/role-arn: "arn:aws:iam::728538925474:role/cg-devx-delta-ci-role"
          extraArgs:
          - --secure
          - --auth-mode=sso
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
            hosts:
              - argo.delta.cgdevx.io
            paths: 
              - /
            pathType: Prefix
            tls:
              - secretName: argo-tls
                hosts:
                  - argo.delta.cgdevx.io
          sso:
            enabled: true
            issuer: https://vault.delta.cgdevx.io/v1/identity/oidc/provider/cgdevx
            clientId:
              name: argo-secrets
              key: client-id
            clientSecret:
              name: argo-secrets
              key: client-secret
            redirectUrl: https://argo.delta.cgdevx.io/oauth2/callback
            scopes:
              - email
              - openid
              - groups
              - user
              - profile
            # RBAC Config. >= v2.12
            rbac:
              enabled: true
        useDefaultArtifactRepo: true
        useStaticCredentials: false
        artifactRepository:
          archiveLogs: false
          s3:
            insecure: false
            bucket: cg-devx-delta-artifacts-repository-cjm7m0hm
            keyFormat: "argo-workflows/artifacts\
              /{{workflow.creationTimestamp.Y}}\
              /{{workflow.creationTimestamp.m}}\
              /{{workflow.creationTimestamp.d}}\
              /{{workflow.uid}}\
              /{{workflow.name}}\
              /{{pod.name}}"
            endpoint: s3.amazonaws.com
            region: eu-west-2
            useSDKCreds: true
            encryptionOptions:
              enableEncryption: false
    chart: argo-workflows
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
