apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cwfts
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '30'
spec:
  project: default
  source:
    repoURL: <GIT_REPOSITORY_GIT_URL>
    path: gitops_pipelines/delivery/clusters/cc_cluster/core_services/components/argo-workflows/cluster-workflow-templates
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
