apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-secret-reader
  namespace: argo
  annotations:
    argocd.argoproj.io/sync-wave: '0'
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-secret-reader
  namespace: argo
  annotations:
    argocd.argoproj.io/sync-wave: '0'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-secret-reader
subjects:
- kind: ServiceAccount
  name: argo-workflow-controller
  namespace: argo
- kind: ServiceAccount
  name: argo-workflow
  namespace: argo
