---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-admin
  namespace: argo
  annotations:
    argocd.argoproj.io/sync-wave: '0'
    workflows.argoproj.io/rbac-rule: "'admins' in groups"
    workflows.argoproj.io/rbac-rule-precedence: '2'
secrets:
  - name: argo-admin
---
apiVersion: v1
kind: Secret
metadata:
  name: argo-admin
  namespace: argo
  annotations:
    kubernetes.io/service-account.name: argo-admin
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-admin-crb
  namespace: argo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-admin
subjects:
  - kind: ServiceAccount
    name: argo-admin
    namespace: argo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-developer
  namespace: argo
  annotations:
    argocd.argoproj.io/sync-wave: '0'
    workflows.argoproj.io/rbac-rule: "'developers' in groups"
    workflows.argoproj.io/rbac-rule-precedence: '1'
secrets:
  - name: argo-developer
---
apiVersion: v1
kind: Secret
metadata:
  name: argo-developer
  namespace: argo
  annotations:
    kubernetes.io/service-account.name: argo-developer
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-developer-crb
  namespace: argo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-view
subjects:
  - kind: ServiceAccount
    name: argo-developer
    namespace: argo
