{
 "title": "NodeJS Request Duration Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Request Duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests Per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (service) (rate(http_request_duration_seconds_count{}[2m]))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Reqeust Duration Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "label_replace(sum by (le) (increase(http_request_duration_seconds_bucket{}[$__rate_interval])), \"le\", \"Inf\", \"le\", \"\\\\+Inf\")",
     "legendFormat": "{{le}} "
    }
   ]
  },
  {
   "title": "Reqeust Duration Summary",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (le) (rate(http_request_duration_seconds_bucket{}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Request Duration (Stacked All Buckets)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (le) (rate(http_request_duration_seconds_bucket{}[3m]))\n",
     "legendFormat": "Requests > {{le}}s per second"
    }
   ]
  },
  {
   "title": "Request Duration (Unstacked Buckets)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (rate(http_request_duration_seconds_bucket{le=\"0.03\"}[3m])) - sum (rate(http_request_duration_seconds_bucket{le=\"0.003\"}[3m]))",
     "legendFormat": "0.003  <  t  <  0.03"
    },
    {
     "expr": "sum (rate(http_request_duration_seconds_bucket{le=\"0.1\"}[3m])) - sum (rate(http_request_duration_seconds_bucket{le=\"0.03\"}[3m]))",
     "legendFormat": "0.03  <  t  <  0.1"
    },
    {
     "expr": "sum (rate(http_request_duration_seconds_bucket{le=\"0.3\"}[3m])) - sum (rate(http_request_duration_seconds_bucket{le=\"0.1\"}[3m]))",
     "legendFormat": "0.1  <  t  < 0.3"
    },
    {
     "expr": "sum (rate(http_request_duration_seconds_bucket{le=\"1.5\"}[3m])) - sum (rate(http_request_duration_seconds_bucket{le=\"0.3\"}[3m]))",
     "legendFormat": "0.3  <  t  <  1.5"
    },
    {
     "expr": "sum (rate(http_request_duration_seconds_bucket{le=\"10\"}[3m])) - sum (rate(http_request_duration_seconds_bucket{le=\"1.5\"}[3m]))",
     "legendFormat": "1.5  <  t  <  10"
    },
    {
     "expr": "sum (rate(http_request_duration_seconds_bucket{le=\"+Inf\"}[3m])) - sum (rate(http_request_duration_seconds_bucket{le=\"10\"}[3m]))",
     "legendFormat": "10  <  t"
    }
   ]
  },
  {
   "title": "Percentage of requests shorter than 0.3 seconds",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum by (service) (increase(http_request_duration_seconds_bucket{le=\"0.3\"}[1d])) / sum by (service) (increase(http_request_duration_seconds_count{}[1d]))) * 100"
    }
   ]
  },
  {
   "title": "Request Duration (Stacked Buckets)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (service, le) (rate(http_request_duration_seconds_count{}[3m]) - ignoring (le) group_right rate(http_request_duration_seconds_bucket{le!=\"+Inf\"}[3m]))",
     "legendFormat": "Requests > {{le}}s per second"
    }
   ]
  },
  {
   "title": "Percentage of requests shorter than 0.3 seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "(sum by (service) (rate(http_request_duration_seconds_bucket{le=\"0.3\"}[2m])) / sum by (service) (rate(http_request_duration_seconds_count{}[2m]))) * 100"
    }
   ]
  }
 ]
}