{
 "title": "Tracee Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "TRC evens",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"tracee\", job=\"tracee/tracee\", namespace=\"tracee\"} |= `TRC` [15m]))"
    }
   ]
  },
  {
   "title": "Events Throughput",
   "type": "timeseries",
   "description": "The rate of events processed and lost",
   "gridPos": { "h": 22, "w": 13, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "rate(tracee_ebpf_events_total[1m])",
     "legendFormat": "events/sec"
    },
    {
     "expr": "rate(tracee_ebpf_lostevents_total[1m])",
     "legendFormat": "lost_events/sec"
    }
   ]
  },
  {
   "title": "EBPF Events Produced",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tracee_ebpf_events_total" }
   ]
  },
  {
   "title": "Lost Events",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tracee_ebpf_lostevents_total", "legendFormat": "Buffer Lost Events" },
    {
     "expr": "tracee_ebpf_network_lostevents_total",
     "legendFormat": "Network Lost Events"
    },
    {
     "expr": "tracee_ebpf_write_lostevents_total",
     "legendFormat": "Write Lost Events"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "{app=\"tracee\", job=\"tracee/tracee\", namespace=\"tracee\"}|= `TRC`",
     "maxLines": 1000
    }
   ]
  }
 ]
}