apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sonarqube-admin
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  target:
    name: sonarqube-admin
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv-secret
  refreshInterval: 10s
  dataFrom:
    - extract:
        key: secret/sonarqube/admin-auth
