apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  project: core
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.12.2
    helm:
      values: |-
        controller:
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
              additionalLabels:
                release: kube-prometheus-stack
          publishService:
            enabled: true
          service:
            annotations:
              # <INGRESS_ANNOTATIONS>
          extraArgs:
            publish-service: ingress-nginx/ingress-nginx-controller
            enable-ssl-passthrough: true
        commonLabels:
          cg-devx.cost-allocation.cost-center: platform
          cg-devx.metadata.owner: <GITOPS_REPOSITORY_NAME>-admin
          cg-devx.metadata.service: ingress-nginx
          cg-devx.metadata.chart-version: 4.12.2
          cg-devx.metadata.version: 1.12.2
    chart: ingress-nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
