apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-toolkit-ingress-nginx
  namespace: ingress-nginx
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k8s-toolkit-ingress-nginx
  namespace: ingress-nginx
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
    verbs:
      - get
      - watch
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-toolkit-ingress-nginx
  namespace: ingress-nginx
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: k8s-toolkit-ingress-nginx
subjects:
  - kind: ServiceAccount
    name: k8s-toolkit-ingress-nginx
    namespace: ingress-nginx
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '20'
  name: wait-ingress-nginx
  namespace: ingress-nginx
spec:
  template:
    spec:
      containers:
        - args:
            - rollout
            - status
            - deployment
            - --namespace
            - ingress-nginx
            - -l
            - app.kubernetes.io/name=ingress-nginx
            - --timeout=90s
            - --watch=true
          image: registry.hub.docker.com/bitnami/kubectl:<KUBECTL_VERSION>
          imagePullPolicy: IfNotPresent
          name: wait
      restartPolicy: OnFailure
      serviceAccountName: k8s-toolkit-ingress-nginx
