apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atlantis
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  project: core
  source:
    repoURL: https://runatlantis.github.io/helm-charts
    chart: atlantis
    targetRevision: 4.15.3
    helm:
      values: |-
        statefulSet:
          annotations:
            secret.reloader.stakater.com/reload: "atlantis-envs-secrets"
        atlantisUrl: https://<IAC_PR_AUTOMATION_INGRESS_URL>
        orgAllowlist: <GIT_REPOSITORY_ROOT>/*
        hidePrevPlanComments: true
        serviceAccount:
          create: true
          mount: true
          annotations:
            <K8S_ROLE_MAPPING>: "<IAC_PR_AUTOMATION_IAM_ROLE_RN>"
        resources:
          limits:
            cpu: 400m
            memory: 1Gi
          requests:
            cpu: 400m
            memory: 512Mi
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
          path: /
          host: <IAC_PR_AUTOMATION_INGRESS_URL>
          ingressClassName: "nginx"
          tls:
            - secretName: atlantis-tls
              hosts:
                - <IAC_PR_AUTOMATION_INGRESS_URL>
        basicAuthSecretName: atlantis-basic-auth-secrets 
        defaultTFVersion: 1.3.9
        loadEnvFromSecrets:
          - atlantis-envs-secrets
        repoConfig: |
          ---
          repos:
          - id: <GIT_REPOSITORY_ROOT>/*
            workflow: default
            allowed_overrides: [apply_requirements]
            apply_requirements: [mergeable]
        volumeClaim:
          dataStorage: 20Gi
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: atlantis
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 5m0s
        factor: 2
