apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: atlantis-envs-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  target:
    name: atlantis-envs-secrets
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv-secret
  refreshInterval: 10s
  dataFrom:
    - extract:
        key: /atlantis/envs-secrets
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: atlantis-basic-auth-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  target:
    name: atlantis-basic-auth-secrets
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv-secret
  refreshInterval: 10s
  dataFrom:
    - extract:
        key: /atlantis/basic-auth-secrets