---
apiVersion: 'external-secrets.io/v1'
kind: ExternalSecret
metadata:
  name: harbor-admin
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  target:
    name: harbor-admin
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv-secret
  refreshInterval: 10s
  dataFrom:
    - extract:
        key: secret/harbor/admin-auth
---
apiVersion: 'external-secrets.io/v1'
kind: ExternalSecret
metadata:
  name: docker-config
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  target:
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .dockerconfig | toString }}"
    name: docker-config
    creationPolicy: Owner
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv-secret
  refreshInterval: 10s
  data:
  - secretKey: "dockerconfig"
    remoteRef:
      property: dockerconfig
      key: dockerconfigjson