apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: oauth2-proxy-secrets
  namespace: oauth2-proxy
spec:
  target:
    name: oauth2-proxy-secrets
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv-secret
  refreshInterval: 10s
  data:
    - remoteRef:
        key: oidc/oauth2_backstage
        property: client_id
      secretKey: client-id
    - remoteRef:
        key: oidc/oauth2_backstage
        property: client_secret
      secretKey: client-secret
    - remoteRef:
        key: oauth2/cookie
        property: backstage_cookie_secret
      secretKey: cookie-secret


