apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  cg-devx.cost-allocation.cost-center: platform
  cg-devx.metadata.owner: <GITOPS_REPOSITORY_NAME>-admin
  cg-devx.metadata.service: proxy.oauth2
  cg-devx.metadata.version: latest

resources:
- oauth2-proxy.yaml
- oauth2-proxy-ing.yaml
- externalsecrets.yaml

generatorOptions:
  disableNameSuffixHash: true
