apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: oauth2-proxy

resources:
- oauth2-proxy.yaml
- oauth2-proxy-ing.yaml
- externalsecrets.yaml

generatorOptions:
  disableNameSuffixHash: true
