apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: eslint-wft
spec:
  templates:
  - name: eslint
    script:
      image: "{{workflow.parameters.registry-mirror}}/{{workflow.parameters.dockerhub-proxy-prefix}}/pipelinecomponents/eslint:latest"
      imagePullPolicy: IfNotPresent
      env:
        - name: WLSERVICE
          value: "{{workflow.parameters.wl-service-name}}"
      command: [sh]
      source: |
          echo $WLSERVICE
          cd /build/$WLSERVICE
          ls src/**/*.ts* > /dev/null 2>&1 || { echo "Nothing to lint, exiting"; exit 1;}
          npm -s  --prefix /app install  eslint-config-standard-with-typescript eslint-plugin-prettier eslint-config-prettier eslint-plugin-only-warn
          eslint --plugin only-warn 'src/**/*.ts?'
      volumeMounts:
        - name: build
          mountPath: /build

