apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: git-clone-wft
spec:
  templates:
  - name: git-clone
    inputs:
      artifacts:
      - name: git-src
        path: /src
        git:
          repo: "{{workflow.parameters.repo}}"
          revision: "{{workflow.parameters.tag}}" 
          sshPrivateKeySecret:
             name: ci-secrets
             key: SSH_PRIVATE_KEY
          depth: 1        

    script:
        image: "{{workflow.parameters.dockerhub-registry-proxy}}/alpine/git" 
        imagePullPolicy: IfNotPresent
        env:
          - name: WL_SERVICE
            value: "{{workflow.parameters.wl-service-name}}"
          - name: REGISTRY_MIRROR
            value: "{{workflow.parameters.dockerhub-registry-proxy}}"
        command: [sh]
        source: |
          echo "WL_SERVICE: $WL_SERVICE"
          cp -rv /src/$WL_SERVICE  /build/
          if [[ $REGISTRY_MIRROR ]]
          then
            cd /build/$WL_SERVICE
            sed -r -i.orig "s/FROM\s+(\S+(\/)\S+)/FROM $REGISTRY_MIRROR\/\1/;s/FROM\s+(\S+)/FROM $REGISTRY_MIRROR\/library\/\1/" Dockerfile
          fi
          cat /src/$WL_SERVICE/?ockerfile
        volumeMounts:
          - mountPath: "/build"
            name: build
            
