apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: trivy-fs-scan-wft
#TODO:
# in the end: clean up unpacked-fs
# script for untar and run trivy fs
spec:
  templates:
  - name: trivy-fs-scan
    container:
        image: "{{workflow.parameters.registry-mirror}}/{{workflow.parameters.dockerhub-proxy-prefix}}/aquasec/trivy"
        imagePullPolicy: IfNotPresent
        args:
          - fs
          -  /build/{{workflow.parameters.wl-service-name}}
        volumeMounts:
          - name: build
            mountPath: /build

