apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: tslint-wft
spec:
  templates:
  - name: tslint
    container:
      image: "{{workflow.parameters.registry-mirror}}/{{workflow.parameters.dockerhub-proxy-prefix}}/pipelinecomponents/tslint"
      imagePullPolicy: IfNotPresent
      command: ["tslint", "-c", "/build/{{workflow.parameters.wl-service-name}}/tslint.json", "/build/{{workflow.parameters.wl-service-name}}/src/**/*.ts"]
      volumeMounts:
        - name: build
          mountPath: /build

