apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubernetes-toolkit
  namespace: external-dns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubernetes-toolkit
  namespace: external-dns
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
    verbs:
      - get
      - watch
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubernetes-toolkit
  namespace: external-dns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubernetes-toolkit
subjects:
  - kind: ServiceAccount
    name: kubernetes-toolkit
    namespace: external-dns
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '20'
  name: kubernetes-toolkit
  namespace: external-dns
spec:
  template:
    spec:
      containers:
        - args:
            - rollout
            - status
            - deployment
            - --namespace
            - external-dns
            - -l
            - app.kubernetes.io/name=external-dns
            - --timeout=90s
            - --watch=true
          image: registry.hub.docker.com/bitnami/kubectl:<KUBECTL_VERSION>
          imagePullPolicy: IfNotPresent
          name: kubernetes-toolkit
      restartPolicy: OnFailure
      serviceAccountName: kubernetes-toolkit
