---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-oidc-restart-job
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-oidc-restart-job
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-oidc-restart-job
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-oidc-restart-job
subjects:
  - kind: ServiceAccount
    name: argocd-oidc-restart-job
    namespace: argocd
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '110'
    argocd.argoproj.io/hook: PostSync
  name: argocd-oidc-restart-job
spec:
  template:
    spec:
      containers:
        - name: argocd-oidc-restart-job
          image: registry.hub.docker.com/bitnami/kubectl:<KUBECTL_VERSION>
          command:
            - /bin/sh
            - -c
            - kubectl -n argocd rollout restart deployment/argocd-server
      restartPolicy: OnFailure
      serviceAccountName: argocd-oidc-restart-job
