---
apiVersion: "external-secrets.io/v1alpha1"
kind: ExternalSecret
metadata:
  name: argocd-oidc-secret
  labels:
    app.kubernetes.io/part-of: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '-10'
spec:
  target:
    name: argocd-oidc-secret
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv-secret
  refreshInterval: 10s
  data:
    - remoteRef:
        key: oidc/argocd
        property: client_secret
      secretKey: clientSecret
    - remoteRef:
        key: oidc/argocd
        property: client_id
      secretKey: clientId
---
apiVersion: "external-secrets.io/v1alpha1"
kind: ExternalSecret
metadata:
  name: argocd-webhook-secret
  labels:
    app.kubernetes.io/part-of: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '-10'
spec:
  target:
    name: argocd-webhook-secret
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv-secret
  refreshInterval: 10s
  data:
    - remoteRef:
        key: cd-secrets
        property: cd_webhook_secret
      secretKey: cd_webhook_secret