apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - argocd-ui-ingress.yaml
  - externalsecrets.yaml
  - argocd-oidc-restart-job.yaml
  - github.com:argoproj/argo-cd.git/manifests/ha/cluster-install?ref=v2.6.4
  - argocd-namespace.yaml

patchesStrategicMerge:
  - argocd-cm.yaml
  - argocd-cmd-params-cm.yaml
  - argocd-rbac-cm.yaml

generatorOptions:
  disableNameSuffixHash: true
