apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - git@github.com:CGDevX-Demo/cg-devx-gitops-test.git/installation-manifests/argocd
  - argocd-ui-ingress.yaml
  - externalsecrets.yaml
  - argocd-oidc-restart-job.yaml

patchesStrategicMerge:
  - argocd-cm.yaml

generatorOptions:
  disableNameSuffixHash: true
