apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/kubevirt/kubevirt/releases/download/v1.2.2/kubevirt-operator.yaml
  - kubevirt-cr.yaml

transformers:
  - label-transformer.yaml