---
apiVersion: builtin
kind: LabelTransformer
metadata:
  name: kubevirt-common-labels
labels:
  cg-devx.cost-allocation.cost-center: "platform"
  cg-devx.metadata.owner: "<GITOPS_REPOSITORY_NAME>-admin"
  cg-devx.metadata.service: "virtualization.kubevirt"
  cg-devx.metadata.version: "1.2.2"
fieldSpecs:
- path: metadata/labels
  create: true
- path: spec/template/metadata/labels
  create: true
  kind: Deployment
