---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: controller-manager
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  target:
    name: controller-manager
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv-secret
  data:
  - remoteRef:
      key: ci-secrets
      property: PERSONAL_ACCESS_TOKEN
    secretKey: github_token
---
apiVersion: 'external-secrets.io/v1beta1'
kind: ExternalSecret
metadata:
  name: docker-config
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  target:
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .dockerconfig | toString }}"
    name: docker-config
    creationPolicy: Owner
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv-secret
  refreshInterval: 10s
  data:
  - secretKey: "dockerconfig"
    remoteRef:
      property: dockerconfig
      key: dockerconfigjson