apiVersion: 'external-secrets.io/v1beta1'
kind: ExternalSecret
metadata:
  name: grafana-secrets
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  target:
    name: grafana-secrets
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv-secret
  refreshInterval: 10s
  data:
    - remoteRef:
        key: oidc/grafana
        property: client_id
      secretKey: GF_AUTH_GENERIC_OAUTH_CLIENT_ID
    - remoteRef:
        key: oidc/grafana
        property: client_secret
      secretKey: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
    - remoteRef:
        key: secret/grafana-secrets
        property: GRAFANA_USER
      secretKey: grafana-user
    - remoteRef:
        key: secret/grafana-secrets
        property: GRAFANA_PASS
      secretKey: grafana-pass