apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab-runner
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: gitlab-runner
  project: default
  source:
    repoURL: 'https://charts.gitlab.io'
    targetRevision: 0.77.2
    helm:
      values: |-
        gitlabUrl: https://gitlab.com
        replicas: 2
        concurrent: 10
        hostNetwork: true
        unregisterRunners: true
        rbac:
          create: true
          clusterWideAccess: true
        runners:
          secret: gitlab-runner
          privileged: true
          serviceAccountName: gitlab-runner
          config: |
            [[runners]]
              [runners.kubernetes]
                image = "ubuntu:24.04"
                privileged = false
                service_account = "gitlab-runner"
              [[runners.kubernetes.volumes.empty_dir]]
                name = "docker-certs"
                mount_path = "/certs/client"
                medium = "Memory"
        deploymentLabels:
          cg-devx.cost-allocation.cost-center: platform
          cg-devx.metadata.owner: <GITOPS_REPOSITORY_NAME>-admin
          cg-devx.metadata.service: vsc.runner
          cg-devx.metadata.chart-version: 0.77.2
          cg-devx.metadata.version: 0.27.6
        podLabels:
          cg-devx.cost-allocation.cost-center: platform
          cg-devx.metadata.owner: <GITOPS_REPOSITORY_NAME>-admin
          cg-devx.metadata.service: vsc.runner
          cg-devx.metadata.chart-version: 0.77.2
          cg-devx.metadata.version: 0.27.6    
    chart: gitlab-runner
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitlab-runner-argo-workflows-admin
  annotations:
    argocd.argoproj.io/sync-wave: '2'
subjects:
  - kind: ServiceAccount
    name: gitlab-runner
    namespace: gitlab-runner
roleRef:
  kind: ClusterRole
  name: argo-admin
  apiGroup: rbac.authorization.k8s.io
