apiVersion: 'external-secrets.io/v1beta1'
kind: ExternalSecret
metadata:
  name: gitlab-runner
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  target:
    name: gitlab-runner
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv-secret
  refreshInterval: 10s
  data:
    - remoteRef:
        key: gitlab-runner
        property: runner_token
      secretKey: runner-token
    - remoteRef:
        key: gitlab-runner
        property: runner_token
      secretKey: runner-registration-token
