apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  project: core
  source:
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.8.1
    helm:
      values: |-
        serviceAccount:
          create: false
          name: external-secrets
        commonLabels:
          cg-devx.cost-allocation.cost-center: platform
          cg-devx.metadata.owner: <GITOPS_REPOSITORY_NAME>-admin
          cg-devx.metadata.service: external-secrets-operator
          cg-devx.metadata.chart-version: 0.8.1
          cg-devx.metadata.version: 0.8.1
    chart: external-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jqPathExpressions:
        - .spec.conversion.webhook.clientConfig.caBundle
        - .spec.conversion.webhook.clientConfig.service.name
        - .spec.conversion.webhook.clientConfig.service.namespace
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[]?.clientConfig.caBundle
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eso-kubernetes-external-secrets-auth
  annotations:
    argocd.argoproj.io/sync-wave: '40'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:auth-delegator'
subjects:
  - kind: ServiceAccount
    name: external-secrets
    namespace: external-secrets-operator
