apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: black-wft
spec:
  templates:
  - name: black
    container:
      image: pyfound/black
      imagePullPolicy: IfNotPresent
      command: ["black", "--check", "-v", "/{{workflow.parameters.workload}}"]
      volumeMounts:
        - name: build
          mountPath: "{{workflow.parameters.workload}}"

