apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: minimalistic-app-dag-wft
spec:
  arguments:
    parameters:
      - name: image
        value: harbor.delta.cgdevx.io/minimalistic-app-test/minimalistic-app
      - name: tag
        value: "0.3"
      - name: workload
        value: minimalistic-app-test
      - name: wl-service-name
        value: minimalistic-app
      - name: revision
        value: "v1.0"
      - name: repo
        value: git@github.com:CloudGeometry/cg-devx-minimalistic-demo-app.git
  volumeClaimTemplates:
    - metadata:
        name: build
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 4Gi
  entrypoint: ci-sequence
  onExit: exit-handler
  volumes:
    #  - name: build
      #    persistentVolumeClaim:
#claimName: build-volume-claim
  - name: kaniko-secret
    secret:
      secretName: harbcred
      items:
        - key: .dockerconfigjson
          path: config.json

  templates:
  - name: ci-sequence
    dag:
      tasks:
      - name: git-clone
        templateRef:
          name: git-clone-wft
          template: git-clone
      - name: linter
        dependencies: [git-clone]
        templateRef:
          name: tslint-wft
          template: tslint
      - name: kaniko
        dependencies: [git-clone]
        templateRef: 
          name: kaniko-wft
          template: kaniko
      - name: trivy-fs-scan
        dependencies: [git-clone]
        templateRef:
          name: trivy-fs-scan-wft
          template: trivy-fs-scan
      - name: crane
        dependencies: [git-clone,linter,kaniko,trivy-fs-scan]
        templateRef: 
            name: crane-wft
            template: crane
  - name: exit-handler
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo  {{workflow.name}} {{workflow.status}} {{workflow.duration}}"]
  
