apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '10'
  name: kubecost
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kubecost
    server: https://kubernetes.default.svc
  project: core
  source:
    chart: cost-analyzer
    repoURL: https://kubecost.github.io/cost-analyzer/
    targetRevision: 2.2.2
    helm:
      releaseName: kubecost
      values: |
        global:
          prometheus:
            enabled: false
            fqdn: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
          grafana:
            # disable embedded grafana when wil upgrade to v2.3
            # https://github.com/kubecost/cost-analyzer-helm-chart/issues/3219
            enabled: true
            domainName: <GRAFANA_INGRESS_URL>
            scheme: "https"
            proxy: false
        kubecostMetrics:
          exporter:
            enabled: true
            serviceMonitor:
              enabled: true
        networkCosts:
          enabled: true
          config:
            services:
              # enable only required cloud hosting
              # google-cloud-services: false
              # amazon-web-services: true
              # azure-cloud-services: false
        serviceMonitor:
          enabled: true
          networkCosts:
            enabled: true
        grafana:
          sidecar:
            dashboards:
              enabled: true
            datasources:
              enabled: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true