apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tracee
  namespace: tracee
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: tracee
  endpoints:
  - port: metrics
