apiVersion: v1
kind: Service
metadata:
  name: tracee
  labels:
    app.kubernetes.io/instance: tracee
    app.kubernetes.io/name: tracee
spec:
  ports:
    - name: metrics
      protocol: TCP
      port: 3366
      targetPort: 3366
  selector:
    app.kubernetes.io/instance: tracee
    app.kubernetes.io/name: tracee
  type: ClusterIP


