apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '10'
  name: tracee
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: tracee
    server: https://kubernetes.default.svc
  project: core
  source:
    chart: tracee
    repoURL: https://aquasecurity.github.io/helm-charts/
    targetRevision: 0.15.1
    helm:
      releaseName: tracee
      # values: |
      #   example: value
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true