apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '10'
  name: tracee
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: tracee
    server: https://kubernetes.default.svc
  project: core
  source:
    chart: tracee
    repoURL: https://aquasecurity.github.io/helm-charts/
    targetRevision: 0.15.1
    helm:
      releaseName: tracee
      values: |
        config:
          metrics: true
        labels:
          cg-devx.cost-allocation.cost-center: platform
          cg-devx.metadata.owner: <GITOPS_REPOSITORY_NAME>-admin
          cg-devx.metadata.service: runtime-security.tracee
          cg-devx.metadata.chart-version: 0.15.1
          cg-devx.metadata.version: 0.15.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
