apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/kubevirt/containerized-data-importer/releases/download/v1.54.2/cdi-operator.yaml
  - cdi-cr.yaml

transformers:
  - label-transformer.yaml