---
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: build-chain-cwft
spec:
  volumeClaimTemplates:
  - metadata:
      name: build
    spec:
      accessModes: [ReadWriteOnce]
      resources:
        requests:
          storage: 8Gi
  volumes:
    - name: kaniko-secret
      secret:
        secretName: proxy-docker-config
        items:
          - key: .dockerconfigjson
            path: config.json
  imagePullPolicy: IfNotPresent
  imagePullSecrets: 
    - name: proxy-docker-config
  entrypoint: ci-sequence
  templates:
    - name: ci-sequence
      dag:
        tasks:
        - name: git-clone
          templateRef:
            name: git-clone-cwft
            template: git-clone
            clusterScope: true
        - name: kaniko
          dependencies: [git-clone]
          templateRef: 
            name: kaniko-s3-cwft
            template: kaniko
            clusterScope: true
        - name: trivy-fs-scan
          dependencies: [git-clone]
          templateRef:
            name: trivy-fs-s3-cwft
            template: trivy-fs-scan
            clusterScope: true
        - name: megalinter
          dependencies: [git-clone]
          templateRef:
            name: megalinter-cwft
            template: megalinter
            clusterScope: true

