---
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: crane-s3-cwft
spec:
  templates:
    - name: crane
      inputs:
        artifacts:
          - name: tar-build
            path: /tmp/{{workflow.parameters.wl-service-name}}.tar
            s3:
              key: "{{workflow.parameters.workload-name}}/{{workflow.parameters.tag}}/{{workflow.parameters.wl-service-name}}-tar"

      container:
        image: '{{workflow.parameters.gcr-registry-proxy}}/go-containerregistry/crane'
        imagePullPolicy: IfNotPresent
        args:
          - push
          - /tmp/{{workflow.parameters.wl-service-name}}.tar
          - '{{workflow.parameters.registry}}/{{workflow.parameters.workload-name}}/{{workflow.parameters.wl-service-name}}:{{workflow.parameters.tag}}'
        volumeMounts:
          - name: crane-secret
            mountPath: /home/nonroot/.docker

