---
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: git-clone-no-proxy-cwft
spec:
  templates:
    - name: git-clone
      inputs:
        artifacts:
          - name: git-src
            path: /src
            git:
              repo: '{{workflow.parameters.repo}}'
              revision: '{{workflow.parameters.tag}}'
              sshPrivateKeySecret:
                name: ci-secrets
                key: SSH_PRIVATE_KEY
              depth: 1
      script:
        image: '{{workflow.parameters.dockerhub-registry-proxy}}/alpine/git'
        imagePullPolicy: IfNotPresent
        env:
          - name: WL_SERVICE
            value: '{{workflow.parameters.wl-service-name}}'
        command: [sh]
        source: |
          echo "WL_SERVICE: $WL_SERVICE"
          echo "Dockerfile-parameter {{workflow.parameters.dockerfile}}"
          cp -r /src/*  /build/  && echo "Copy successful."
        volumeMounts:
          - mountPath: /build
            name: build
