---
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: git-clone-cwft
spec:
  templates:
    - name: git-clone
      inputs:
        artifacts:
          - name: git-src
            path: /src
            git:
              repo: '{{workflow.parameters.repo}}'
              revision: '{{workflow.parameters.tag}}'
              sshPrivateKeySecret:
                name: ci-secrets
                key: SSH_PRIVATE_KEY
              depth: 1
      script:
        image: '{{workflow.parameters.dockerhub-registry-proxy}}/alpine/git'
        imagePullPolicy: IfNotPresent
        env:
          - name: WL_SERVICE
            value: '{{workflow.parameters.wl-service-name}}'
          - name: WL_SERVICE_DIR
            value: '{{workflow.parameters.wl-service-dir}}'
          - name: REGISTRY_MIRROR
            value: '{{workflow.parameters.registry}}'
          - name: DOCKERHUB_REGISTRY_PROXY
            value: '{{workflow.parameters.dockerhub-registry-proxy}}'

          
        command: [sh]
        source: |
          DOCKERHUB_PROXY_PREFIX=`basename $DOCKERHUB_REGISTRY_PROXY`
          echo "WL_SERVICE: $WL_SERVICE"
          echo "Dockerfile-parameter {{workflow.parameters.dockerfile}}"
          cp -r /src/*  /build/  && echo "Copy successful."
          if [[ $REGISTRY_MIRROR ]]
          then
            cd /build/$WL_SERVICE_DIR
            sed -r -i.orig "s/FROM\s+(\S+(\/)\S+)/FROM $DOCKERHUB_PROXY_PREFIX\/\1/;s/FROM\s+(\S+)/FROM $DOCKERHUB_PROXY_PREFIX\/library\/\1/" Dockerfile
            cat Dockerfile
          fi
        volumeMounts:
          - mountPath: /build
            name: build
