---
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: kaniko-no-proxy-cwft
spec:
  templates:
    - name: kaniko
      container:
        image: '{{workflow.parameters.gcr-registry-proxy}}/kaniko-project/executor'
        imagePullPolicy: IfNotPresent
        args:
          - --dockerfile={{workflow.parameters.dockerfile}}
          - --context=dir:///workspace/{{workflow.parameters.build-context}}
          - --no-push
          - --tar-path=/workspace/{{workflow.parameters.wl-service-name}}.tar
          - --snapshot-mode=time
          - --use-new-run
          - --cache=false
          - --cache-run-layers
          - --cache-repo={{workflow.parameters.registry}}/kaniko-cache/{{workflow.parameters.workload-name}}-{{workflow.parameters.wl-service-name}}
        volumeMounts:
          - name: kaniko-secret
            mountPath: /kaniko/.docker
          - name: build
            mountPath: /workspace
