---
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: kaniko-s3-p-experimental-cwft
spec:
  templates:
    - name: kaniko
      archiveLocation:
        archiveLogs: true
      inputs:
        artifacts:
          - name: git-src
            path: /build
            git:
              repo: '{{workflow.parameters.repo}}'
              revision: '{{workflow.parameters.tag}}'
              sshPrivateKeySecret:
                name: ci-secrets
                key: SSH_PRIVATE_KEY
              depth: 1
      container:
        image: '{{workflow.parameters.gcr-registry-proxy}}/kaniko-project/executor:latest'
        imagePullPolicy: "IfNotPresent"
        args:
          - --registry-map=index.docker.io={{workflow.parameters.dockerhub-registry-proxy}};gcr.io={{workflow.parameters.gcr-registry-proxy}}
          #          - --registry-mirror={{workflow.parameters.kaniko-registry-mirror}}
          # - --skip-default-registry-fallback
          - --dockerfile={{workflow.parameters.dockerfile}}
          - --context=dir:///build/{{workflow.parameters.build-context}}
          - --no-push
          - --tar-path=/tmp/{{workflow.parameters.wl-service-name}}.tar
          - --snapshot-mode=time
          - --use-new-run
          # - --compressed-caching=false
          # #- --cache={{workflow.parameters.kaniko-cache}}
          # - --cache=false
          # - --cache-run-layers
          # - --cache-repo=oci://{{workflow.parameters.kaniko-cache-repo}}/kaniko-cache/{{workflow.parameters.workload-name}}-{{workflow.parameters.wl-service-name}}
          # - --verbosity=debug
        volumeMounts:
          - name: kaniko-secret
            mountPath: /kaniko/.docker
      outputs:
        artifacts:
          - name: tar-build
            path: /tmp/{{workflow.parameters.wl-service-name}}.tar
            s3:
              key: "{{workflow.parameters.workload-name}}/{{workflow.parameters.tag}}/{{workflow.parameters.wl-service-name}}-tar"
            artifactGC:
              strategy: Never
