---
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: megalinter-cwft
spec:
  templates:
    - name: megalinter
      inputs:
        artifacts:
          - name: git-src
            path: /build
            git:
              repo: '{{workflow.parameters.repo}}'
              revision: '{{workflow.parameters.tag}}'
              sshPrivateKeySecret:
                name: ci-secrets
                key: SSH_PRIVATE_KEY
              depth: 1
      container:
        image: "{{workflow.parameters.dockerhub-registry-proxy}}/oxsecurity/megalinter:v8"
        imagePullPolicy: IfNotPresent
        env:
          - name: DEFAULT_WORKSPACE
            value: /build
          - name: REPORT_OUTPUT_FOLDER
            value: /tmp
          - name: DISABLE_ERRORS
            value: "true"
          - name: FILTER_REGEX_INCLUDE
            value: "({{workflow.parameters.wl-service-dir}}|libs/)"
      outputs:
        artifacts:
          - name: megalinter-report-sarif 
            path: /tmp/megalinter-report.sarif 
            s3:
              key: "{{workflow.parameters.workload-name}}/{{workflow.parameters.tag}}/{{workflow.parameters.wl-service-name}}-megalinter-report-sarif"
          - name: megalinter-report-json 
            path: /tmp/mega-linter-report.json
            s3:
              key: "{{workflow.parameters.workload-name}}/{{workflow.parameters.tag}}/{{workflow.parameters.wl-service-name}}-megalinter-report-json"
            artifactGC:
              strategy: Never
