---
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: trivy-fs-scan-cwft
spec:
  templates:
    - name: trivy-fs-scan
      container:
        image: '{{workflow.parameters.dockerhub-registry-proxy}}/aquasec/trivy'
        imagePullPolicy: IfNotPresent
        args: [fs, '--no-progress', '/build/{{workflow.parameters.wl-service-dir}}']
        volumeMounts:
          - name: build
            mountPath: /build
