apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab-agent
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: gitlab-agent
  project: default
  source:
    repoURL: 'https://charts.gitlab.io'
    targetRevision: v2.11.0
    helm:
      values: |-
        serviceAccount:
          name: gitlab-agent
        config:
          kasAddress: wss://kas.gitlab.com
          secretName: gitlab-agent
    chart: gitlab-agent
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitlab-agent-argo-workflows-admin
  annotations:
    argocd.argoproj.io/sync-wave: '2'
subjects:
  - kind: ServiceAccount
    name: gitlab-agent
    namespace: gitlab-agent
roleRef:
  kind: ClusterRole
  name: argo-admin
  apiGroup: rbac.authorization.k8s.io
