apiVersion: 'external-secrets.io/v1beta1'
kind: ExternalSecret
metadata:
  name: gitlab-agent
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  target:
    name: gitlab-agent
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv-secret
  refreshInterval: 10s
  data:
    - remoteRef:
        key: gitlab-agent
        property: token
      secretKey: token
