apiVersion: batch/v1
kind: Job
metadata:
  name: gitlab-agent-wait
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '20'
spec:
  template:
    spec:
      serviceAccountName: argocd-server
      containers:
        - name: gitlab-agent-wait
          image: argoproj/argocd:v2.4.2
          command:
            - /bin/sh
            - -c
            - |
              argocd login argocd.argocd-server.svc.cluster.local --core
              argocd app wait gitlab-agent
      restartPolicy: Never
  backoffLimit: 1
