DEFAULT_ENUM_VALUE = 'unknown'
GITOPS_REPOSITORY_URL = 'https://github.com/CloudGeometry/cgdevx-core.git'
GITOPS_REPOSITORY_BRANCH = 'main'
STATE_INPUT_PARAMS = 'input'
STATE_INTERNAL_PARAMS = 'internal'
STATE_CHECKPOINTS = 'checkpoints'
LOCAL_FOLDER = '.cgdevx'
