DEFAULT_ENUM_VALUE = 'unknown'
GITOPS_REPOSITORY_URL = 'https://github.com/CloudGeometry/cg-devx-core.git'
GITOPS_REPOSITORY_BRANCH = 'main'
STATE_INPUT_PARAMS = 'input'
STATE_CHECKPOINTS = 'checkpoints'
LOCAL_FOLDER = '.cgdevx'
