apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '20'
spec:
  project: core
  source:
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.26.1
    helm:
      parameters:
        - name: server.route.host
          value: vault.<DOMAIN_NAME>
        - name: 'server.ingress.hosts[0].host'
          value: vault.<DOMAIN_NAME>
      values: |-
        server:
          annotations:
            # <SIDECAR_ANNOTATION>
          extraLabels:
            # <ADDITIONAL_LABELS>
          serviceAccount:
            create: true
            name: vault
            annotations:
              <K8S_ROLE_MAPPING>: "<SECRET_MANAGER_IAM_ROLE_RN>"
          affinity: ""
          ha:
            enabled: true
            replicas: 3
            raft:
              enabled: true
              config: |
                ui = true
                listener "tcp" {
                  tls_disable     = 1
                  address         = "[::]:8200"
                  cluster_address = "[::]:8201"
                }
                storage "raft" {
                  path = "/vault/data"
                  retry_join {
                    leader_api_addr = "http://vault-0.vault-internal:8200"
                  }
                  retry_join {
                    leader_api_addr = "http://vault-1.vault-internal:8200"
                  }
                  retry_join {
                    leader_api_addr = "http://vault-2.vault-internal:8200"
                  }
                }
                # <SECRET_MANAGER_SEAL>
                service_registration "kubernetes" {}
          ingress:
            enabled: true
            annotations: 
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
            ingressClassName: "nginx"
            pathType: Prefix
            # When HA mode is enabled and K8s service registration is being used,
            # configure the ingress to point to the Vault active service.
            # activeService: true
            hosts:
              - host: <SECRET_MANAGER_INGRESS_URL>
            tls:
              - secretName: vault-tls
                hosts:
                  - <SECRET_MANAGER_INGRESS_URL>
          ui:
            enabled: true
            serviceType: "ClusterIP"
            serviceNodePort: null
            externalPort: 8200
    chart: vault
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jsonPointers:
        - /webhooks
