apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '20'
spec:
  project: core
  source:
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.22.0
    helm:
      parameters:
        - name: server.route.host
          value: vault.<DOMAIN_NAME>
        - name: 'server.ingress.hosts[0].host'
          value: vault.<DOMAIN_NAME>
      values: |-
        # server:
    chart: vault
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
