apiVersion: v1
preferences: {}
kind: Config

clusters:
- cluster:
    server: <ENDPOINT>
    certificate-authority-data: <CLUSTER_AUTH_BASE64>
  name: <CLUSTER_NAME>

contexts:
- context:
    cluster: <CLUSTER_NAME>
    user: <CLUSTER_NAME>
  name: <CLUSTER_NAME>

current-context: <CLUSTER_NAME>

users:
- name: <CLUSTER_NAME>
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: <CLUSTER_AUTH_COMMAND>
      args:
        -
