apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kyverno
    server: https://kubernetes.default.svc
  project: core
  source:
    chart: kyverno
    repoURL: https://kyverno.github.io/kyverno
    targetRevision: v3.2.7
    helm:
      releaseName: kyverno
      values: |
        commonLabels:
          cg-devx.cost-allocation.cost-center: platform
          cg-devx.metadata.owner: <GITOPS_REPOSITORY_NAME>-admin
          cg-devx.metadata.service: policy-engine.kyverno
          cg-devx.metadata.chart-version: 3.2.7
          cg-devx.metadata.version: 1.12.6
        global:
          imagePullSecrets:
           - name: docker-config
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
