apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kyverno
    server: https://kubernetes.default.svc
  project: core
  source:
    chart: kyverno
    repoURL: https://kyverno.github.io/kyverno
    targetRevision: v3.0.0
    helm:
      releaseName: kyverno
      # values: |
      #   example: value
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true