apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: policy-reporter
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kyverno
    server: https://kubernetes.default.svc
  project: core
  source:
    chart: policy-reporter
    repoURL: https://kyverno.github.io/policy-reporter
    targetRevision: v3.1.4
    helm:
      releaseName: policy-reporter
      values: |
        global:
          labels:
            cg-devx.cost-allocation.cost-center: platform
            cg-devx.metadata.owner: <GITOPS_REPOSITORY_NAME>-admin
            cg-devx.metadata.service: policy-engine.kyverno-policy-reporter
            cg-devx.metadata.chart-version: 3.1.4
            cg-devx.metadata.version: 3.1.1          
        ui:
          enabled: true
        kyvernoPlugin:
          enabled: true
        metrics:
          enabled: true
        global:
          # available plugins
          plugins:
            # enable kyverno for Policy Reporter UI and monitoring
            kyverno: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true