name: Publish to Test PyPI
on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

inputs:
  PYTHON_VERSION:
    description: "Python Version"
    required: false
    default: "3.10.13"
  PACKAGE_DIRECTORY:
    description: "Directory of the package"
    required: false
    default: "./tools"
  # PUBLISH_REGISTRY_PASSWORD:
  #   description: "Password for the user to publish to PyPI. May also be a Token - requires the `PUBLISH_REGISTRY_USERNAME` to be `__token__`"
  #   required: true
  # PUBLISH_REGISTRY_USERNAME:
  #   description: "The username for the registry. Defaults to __token__"
  #   required: false
  #   default: "__token__"
  POETRY_VERSION:
    description: "The version of Poetry to use"
    required: true
    default: "1.8.2"

defaults:
 run:
  working-directory: ./${{ inputs.PACKAGE_DIRECTORY }}

jobs:
  test_pypi_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pip install poetry${{ inputs.POETRY_VERSION }}
        shell: bash
      - name: Set up Python ${{ inputs.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.PYTHON_VERSION }}
          cache: poetry
          check-latest: true
      - run: poetry install
      - run: poetry config repositories.testpypi https://test.pypi.org/legacy/
      - run: poetry config pypi-token.testpypi ${{ secrets.PYPI_TOKEN }}
      - name: Publish package
        run: poetry publish --build -r testpypi