name: PyPi publish
on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v2.0
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
          repository_name: "cg-devx-core"
          repository_url: "https://test.pypi.org/legacy/"
          package_directory: "tools"
          poetry_publish_options: "--dry-run"
          python_version: "3.10.1"
